@portfolio.API_HostAddress = http://localhost:5138

GET {{portfolio.API_HostAddress}}/todos/
Accept: application/json

###

GET {{portfolio.API_HostAddress}}/todos/1
Accept: application/json

###
